/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ba.easyautoproject.view;

import javax.swing.JOptionPane;

/**
 *
 * @author icaro
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCadCli = new javax.swing.JMenuItem();
        jMenuItemCadVeic = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAlugar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemRelFaturamento = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");

        jMenuItemCadCli.setText("Clientes");
        jMenuItemCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadCliActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadCli);

        jMenuItemCadVeic.setText("Veículos");
        jMenuItemCadVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadVeicActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadVeic);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Aluguel");

        jMenuItemAlugar.setText("Alugar");
        jMenuItemAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlugarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAlugar);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Relatórios");

        jMenuItemRelFaturamento.setText("Faturamento");
        jMenuItemRelFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelFaturamentoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRelFaturamento);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadCliActionPerformed
         try {

                cadastroCliente = new CadastroCliente();
                desktopPane.add(cadastroCliente);

                cadastroCliente.show();

            } catch (Exception ex) {

                System.out.println("erro " + ex.getMessage());

            }
    }//GEN-LAST:event_jMenuItemCadCliActionPerformed

    private void jMenuItemCadVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadVeicActionPerformed
        // TODO add your handling code here:
        try {

            cadastroVeiculo = new CadastroVeiculo();
            desktopPane.add(cadastroVeiculo);

            cadastroVeiculo.show();

        } catch (Exception ex) {

            System.out.println("erro " + ex.getMessage());

        }
            
    }//GEN-LAST:event_jMenuItemCadVeicActionPerformed

    private void jMenuItemAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlugarActionPerformed
        // TODO add your handling code here:
        
         try {

                cadastroAluguel = new CadastroAluguel();
                desktopPane.add(cadastroAluguel);

                cadastroAluguel.show();

            } catch (Exception ex) {

                System.out.println("erro " + ex.getMessage());

            }
    }//GEN-LAST:event_jMenuItemAlugarActionPerformed

    private void jMenuItemRelFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelFaturamentoActionPerformed
        // TODO add your handling code here:
       try {

            telarelatorio = new TelaRelatorio();
            desktopPane.add(telarelatorio);

            telarelatorio.show();

        } catch (Exception ex) {

            System.out.println("erro " + ex.getMessage());

        }
    }//GEN-LAST:event_jMenuItemRelFaturamentoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAlugar;
    private javax.swing.JMenuItem jMenuItemCadCli;
    private javax.swing.JMenuItem jMenuItemCadVeic;
    private javax.swing.JMenuItem jMenuItemRelFaturamento;
    // End of variables declaration//GEN-END:variables
    private CadastroVeiculo cadastroVeiculo = null;
    private CadastroCliente cadastroCliente = null;
    private CadastroAluguel cadastroAluguel = null;
    private TelaRelatorio telarelatorio = null;
}
